name: Resource Pack CI

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'
    paths:
      - resource-pack/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build resource pack
        id: upload-resource-pack
        uses: actions/upload-artifact@v4
        with:
          name: openinv-legibility-pack
          path: ./resource-pack/
          compression-level: 9
